### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Arenukvern** [xsoulspace/vuefer#5]
Need to think about how to organize documentation and generate documentation site

The idea is to use something be based on how made [Vue docs](https://github.com/vuejs/vuejs.org) or use [docusaurus](https://docusaurus.io), based on .md files or something similar to https://storybook.js.org to present how to use components

Also is important to show a roadmap for components as it made in the current README

**Comment by eznix86** [comment]
Mkdocs does the job...you can take example here:

Config:

https://github.com/tiangolo/fastapi/blob/master/docs/en/mkdocs.yml


Example:
https://fastapi.tiangolo.com/

**Comment by Arenukvern** [comment]
> Mkdocs does the job...you can take example here:
> 
> Config:
> 
> https://github.com/tiangolo/fastapi/blob/master/docs/en/mkdocs.yml
> 
> Example: https://fastapi.tiangolo.com/

@theArtechnology Thank you for the idea, will look at it!
